## Ejercicios Básicos Numpy

In [14]:
import numpy as np

### Ejercicio 1
Una vez importado numpy, crea un array numpy a partir de la siguiente lista. Muestra por pantalla el tipo de dicha lista, el número de dimensiones que tiene y cuántos elementos hay por dimensión

In [15]:
lista = [100, 80, 180, 140, 25, 170, 200]

In [16]:
lista_np = np.array(lista)
print lista_np.dtype
print lista_np.ndim
print lista_np.shape


int32
1
(7L,)


### Ejercicio 2
Realiza la misma operación pero ahora sobre esta matriz. Imprime el número de dimensiones y cuántos elementos hay

In [17]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [18]:
matriz_np = np.array(matriz)
print matriz_np.ndim
print matriz_np.shape

2
(3L, 3L)


### Ejercicio 3

Dada la siguiente matriz, transformarla en una matriz numpy y hacer un recorrido para que muestre:

el valor de la posición (0,0) es 1

el valor de la posición (0,1) es 2

...

In [19]:
matriz2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]]

In [20]:
matriz2_np = np.array(matriz2)
f,c = matriz2_np.shape
for i in range(f):
    for j in range(c):
        print "El valor de la posicion({},{}) es {}".format(i,j,matriz2_np[i,j])

El valor de la posicion(0,0) es 1
El valor de la posicion(0,1) es 2
El valor de la posicion(0,2) es 3
El valor de la posicion(1,0) es 4
El valor de la posicion(1,1) es 5
El valor de la posicion(1,2) es 6
El valor de la posicion(2,0) es 7
El valor de la posicion(2,1) es 8
El valor de la posicion(2,2) es 9
El valor de la posicion(3,0) es 10
El valor de la posicion(3,1) es 11
El valor de la posicion(3,2) es 12
El valor de la posicion(4,0) es 13
El valor de la posicion(4,1) es 14
El valor de la posicion(4,2) es 15


### Ejercicio 4

Crear una matriz numpy de ceros de 5 filas y 4 columns

Crear una matriz numpy de unos de 10 filas y 10 columnas

Crear un vector numpy con los numeros del 0 al 1000

In [21]:
np.zeros((5,4))
np.ones((10,10))
np.arange(1000)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

### Ejercicio 5

Crear una matriz a de números aleatorios de 4 filas y 3 columnas. Crear una nueva matriz b con los mismos elementos pero en forma de 6 filas y 2 columnas (utilizando reshape). Modificar el elemento (0,0) de b poniéndolo a 0 y mostrar a por pantalla.

In [22]:
a = np.random.rand(4,3)
b = a.reshape(6,2)
b[0,0] = 0
print a

[[ 0.          0.31683934  0.94698457]
 [ 0.42063123  0.50338676  0.90941956]
 [ 0.80260486  0.37205728  0.68449095]
 [ 0.54153386  0.02347168  0.38031297]]


### Ejercicio 5

Dada la siguiente lista, transformarla en un array numpy. Muestra el número de dimensiones. A continuación transfórmalo en un vector columna. Muestra el número de dimensiones

In [23]:
lista = [100, 80, 180, 140, 25, 170, 200]

In [24]:
lista = np.array(lista)
print lista.ndim
lista = lista.reshape(7, 1)
print lista.ndim

1
2


### Ejercicio 6

Intenta repetir el mismo ejercicio que el 4 pero utilizando la función resize. Observa que la función resize modifica las propias dimensiones de a

In [25]:
a = np.random.rand(4,3)
a.resize((6,2))
print a

[[ 0.1287374   0.09710399]
 [ 0.57166197  0.44777483]
 [ 0.55485946  0.116143  ]
 [ 0.5500305   0.33421587]
 [ 0.34407589  0.15168296]
 [ 0.5450903   0.10648726]]


### Ejercicio 7

Crear una matriz a de números aleatorios de 4 filas y 3 columnas. Crear un array b (una sola dimensión) con la concatenación de los elementos de a (utilizando ravel). Cambia el primer elemento poniéndolo a 0 y muestra a

In [26]:
a = np.random.rand(4,3)
b = a.ravel()
b[0] = 0
print a

[[ 0.          0.81855875  0.92683443]
 [ 0.12464408  0.86630176  0.22399359]
 [ 0.4122899   0.81052344  0.85792561]
 [ 0.36659524  0.79286897  0.88263817]]


### Ejercicio 8

Crear una matriz a de números aleatorios de 4 filas y 3 columnas. Crear un array b (una sola dimensión) con la concatenación de los elementos de a. Suma 1 a todos los elementos del array b de tal forma que los valores de a no cambien. 

In [27]:
a = np.random.rand(4,3)
b = a.flatten()
b = b +1
print a
print b

[[ 0.27964984  0.41007313  0.67372361]
 [ 0.08681905  0.42644427  0.98036645]
 [ 0.58219056  0.43970804  0.70246921]
 [ 0.22906892  0.16497879  0.02463799]]
[ 1.27964984  1.41007313  1.67372361  1.08681905  1.42644427  1.98036645
  1.58219056  1.43970804  1.70246921  1.22906892  1.16497879  1.02463799]


### Ejercicio 9

Dada una matriz de unos de dimensión 10x10, modificar de una sola vez a 0 todos los elementos que no estén en el borde de la matriz (primera o última fila o columna).

In [28]:
a = np.ones((10,10))
a[1:9,1:9] = 0
print a

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


### Ejercicio 10

Dada una matriz de unos de dimensión 8x8, modificar (en dos instrucciones) a 0 los elementos necesarios hasta crear una matriz de unos y ceros salteados (tipo tablero de ajedrez) 


In [30]:
a = np.ones((8,8))
a[1::2,1::2] = 0
a[0::2, 0::2] = 0
print a

[[ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]]


### Ejercicio 11

Dada la siguiente matriz, obtener un array numpy con los elementos mayores de 10

In [31]:
matriz = [[ 0, 10, 20], [20, 30, 40]]

In [32]:
matriz = np.array(matriz)
matriz[matriz>10]

array([20, 20, 30, 40])

### Ejercicio 12
Dada la siguiente matriz, obtener una nueva en la que sumamos +1 a todos los elementos positivos y restamos 1 a todos los negativos

In [33]:
matriz = np.random.randn(10,10)

In [34]:
print matriz
matriz[matriz<0] = matriz[matriz<0] -1
matriz[matriz>0] = matriz[matriz>0] +1
print matriz

[[ -1.04999986e+00  -1.64145845e+00   9.89813905e-01  -4.26190967e-01
    8.17320356e-01  -1.55705523e+00   3.10788858e-01   1.96281676e+00
    4.29163296e-01   2.91334657e-01]
 [  2.16704539e-01  -3.13437309e+00   9.32808525e-01   1.43779947e+00
   -1.39267492e+00   1.71416540e-01   1.05150295e+00  -6.49929630e-01
    8.92668728e-01   2.77230561e-03]
 [ -1.41296666e-01  -4.78362658e-01  -1.17627539e-01  -1.37804594e+00
   -1.66643885e+00   1.04115483e+00   3.06623968e-01   1.47593399e+00
    1.95359144e-01   5.57879808e-02]
 [  7.23308731e-01   5.13446505e-01   4.28017612e-01   1.29146968e+00
   -1.49904201e+00   1.46701237e-01   4.69010112e-01  -4.49806930e-01
   -1.38291948e+00  -1.45344499e-01]
 [  7.61080157e-01   5.30858572e-01  -9.40498057e-01   4.14042165e-01
    3.90107110e-01  -1.03875654e-01   1.23551857e+00  -1.76001815e+00
    6.30097953e-01  -1.89901241e+00]
 [  3.54750889e-01  -1.19476812e-01  -5.16046613e-01   7.16327749e-01
    1.02808855e+00  -2.39537905e-01   3.56384

### Ejercicio 13

Dada una matriz de dimensión 10x10 de números aleatorios siguiendo una distribución normal, sumar todos los elementos positivos, todos los negativos y todos los elementos de dicha matriz

In [ ]:
matriz = np.random.randn(10,10)
matriz[matriz>0].sum()
matriz[matriz<0].sum()
matriz.sum()

### Ejercicio 14
Dada un array numpy con los números del 0 al 100, obtener la suma de los números que sean multiplos de 3 y de 5

In [ ]:
array = np.arange(100)
array[np.logical_and(array%3 ==0 ,array%5==0)].sum()

### Ejercicio 15

Dada una matriz de dimensión 100x5 de números aleatorios siguiendo (entre 0 y 1), obtener la suma de cada fila, la suma de cada columna y la suma de todos sus elementos 

In [ ]:
matriz = np.random.rand(100,5)
print matriz.sum(axis=0)
print matriz.sum(axis =1)
print matriz.sum()

### Ejercicio 16

Dado un vector de 100 números aleatorio (entre 0 y 1), cambiar el elemento más pequeño por un 0

In [ ]:
array = np.random.rand(100)
array[np.argmin(array)]=0
print array

### Ejercicio 17

Crea dos matrices, a y b, de números aleatorioes entre 0 y 1 de dimensión 10x10. Obténuna nueva matriz como resultado de sumar las dos matrices a y b

In [35]:
a = np.random.rand(10,10)
b = np.random.rand(10,10)
c = a+ b
print c

[[ 0.51478867  1.08040139  1.21445378  0.99972404  0.69638771  1.46076822
   0.16137944  0.85427173  0.96176539  0.79863066]
 [ 1.33053157  1.73216603  1.42006896  1.52334403  0.48116363  0.51220245
   1.1613379   1.45812524  0.8144015   1.23035572]
 [ 1.26626401  0.86139054  1.25644675  1.08116503  1.61899888  0.70080188
   1.28659481  0.9500055   0.97375995  1.3078319 ]
 [ 0.81381513  0.49525773  0.61547333  0.43195891  0.90346946  0.96224502
   1.68854367  0.77965024  0.22170831  0.66428999]
 [ 0.83689031  1.32678728  0.89278996  1.36516824  0.91920623  1.25794879
   0.4536234   1.6053385   1.49027788  0.22584258]
 [ 0.39454544  0.67129905  1.15202586  0.54405071  0.31438494  0.55384677
   0.23285974  1.44431034  0.22833414  0.99453896]
 [ 0.25018684  1.26750116  0.93384931  1.11491264  1.22533128  1.7113508
   0.72353958  1.96106285  0.48467095  0.92659392]
 [ 0.88617809  0.39746378  1.56087216  0.67075929  0.46924169  0.3018711
   1.34586885  0.91001701  1.11010785  1.17978041]
 [

### Ejercicio 18

Dado la siguiente matriz y el vector, obtener una nueva matriz cuyos elementos seal el resultado de multiplicar elementos a elemento el vector fila por todas las filas de la matriz.

Obtener una cuarta matriz cuyo resultado sea el de multiplicar elemento a elemento el vector por todas las columnas de la matriz

In [37]:
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b = [1, 2, 3]

In [39]:
a = np.array(a)
b = np.array(b)
c1 = a*b
print c1
c2 = a * b.reshape(3, 1)
print c2

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]
[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]


### Ejercicio 19

Dadas las siguientes matrices, a y b, obtener el número de dimensiones de cada una de ellas. Obtener una nueva matriz c de forma se sume la matriz b a cada "capa" de la matriz a

In [40]:
a = np.random.rand(4,3,3)
b = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])


In [41]:
c = a+ b
print c

[[[ 1.78947504  1.43299902  1.47012372]
  [ 2.87671982  2.05172215  2.52375256]
  [ 3.35967978  3.83371944  3.33587597]]

 [[ 1.05780008  1.20681388  1.86854078]
  [ 2.19092829  2.87014479  2.99097507]
  [ 3.77445103  3.99219605  3.02216009]]

 [[ 1.08359705  1.49441005  1.7921449 ]
  [ 2.95259849  2.84673548  2.04468869]
  [ 3.24699202  3.10783192  3.34646848]]

 [[ 1.18943259  1.42347068  1.63098319]
  [ 2.97695637  2.781617    2.79834554]
  [ 3.11156058  3.09617969  3.51358922]]]


### Ejercicio 20

Dados los siguientes vectores a y b, obtener una matriz c de tal forma que $c_{ij} = a_i \times b_j$

In [42]:
a = [1, 2, 3]
b = [1, 2, 3]


In [43]:
a = np.array(a)
b = np.array(b)
a =  a.reshape(3,1)
b = b.reshape(1,3)
c = np.dot(a,b)

print c

[[1 2 3]
 [2 4 6]
 [3 6 9]]
